### ISSUE TITLE
.cojo ouput files

### ISSUE THREAD

**Issue by Nucholas** [jwr-git/pwcoco#2]
Hello,

Could you explain the .cojo ouput files. If I am correct the SNP in the filename is the one the condition analysis in perform on. I have SNPs in the header after the "pC" column and I am not sure what the are referring to. 

Thank you

**Comment by nickhir** [comment]
Hi @jwr-git,
I also have a question regarding this. In the file you linked, it sounds like there should only be one column with a SNP id (which corresponds to the lead SNP). However, in my case, I actually have 32 additional columns (named after SNPs) after the pC column. The SNP in the title of the cojo file is also not the "final" column, but instead in position 29. 
So just to clarify, do the "extra" columns simply describe the LD between the SNP in the row and all SNPs which were selected as "conditionally independent" by cojo?
