### ISSUE TITLE
How should I interpret SNP1 and SNP2 in the .coloc file?

### ISSUE THREAD

**Issue by dsadfsa** [jwr-git/pwcoco#3]
Hi, thanks for the great approach.
How should I interpret SNP1 and SNP2 in the .coloc file, are they both shared genetic variant sites?
The Bayesian co-localization hypothesis requires H4: both traits are associated and share the same single causal variant, but SNP1 and SNP2 are similar to the H3 hypothesis.

**Comment by jwr-git** [comment]
Hi,
You should interpret SNP1 and SNP2 as being the lead SNP of a signal as found by the conditional analysis. The conditional analysis is approximate in nature and is not fine-mapping; therefore, the conditional analysis (COJO) and PWCoCO by extension, is not determining these SNPs to be the _causal_ SNP(s). It might help to imagine that COJO/PWCoCo are capturing the signal at this locus and these SNPs are simply markers to distinguish the signals.
Then, as you say, high H4 means strong evidence of a shared causal variant between the two traits. If PWCoCo finds high H4 evidence for two SNPs, it is important to note that these SNPs may not be the true causal variant, just that the two signals are likely to share a causal variant. If you wanted to then interrogate this further, you would have to apply a method like fine-mapping (e.g. SuSiE).
Hopefully this helps!
