### ISSUE TITLE
Request for features -- A --help / -h option?

### ISSUE THREAD

**Issue by jinghuazhao** [jwr-git/pwcoco#5]
The repository is very interesting and I have downloaded and compiled it on our system.

I feel a minor addition will be very useful, i.e., adding a simple --help or -h command-line option so users would not need to refer to the GitHub README once it is installed; does that sound reasonable? A less relevant point is to have a version so any changes can be tracked -- for now I have used the calendar date on our system.

Thanks very much for making this available.

**Comment by jwr-git** [comment]
Added -- thanks! :)
